### ISSUE TITLE
installation du package ousamabenyounes/log2test en erreur

### ISSUE THREAD

**Issue by fyamani** [ousamabenyounes/log2test#61]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ousamabenyounes/log2test dev-master -> satisfiable by ousamabenyounes/log2test[dev-master].
    - Can only install one of: ousamabenyounes/log2test[1.1, dev-master].
    - Installation request for ousamabenyounes/log2test 1.1 -> satisfiable by ousamabenyounes/log2test[1.1].

**Comment by ousamabenyounes** [comment]
Juste updated the doc for the install step

now you just have to do: 
git clone https://github.com/ousamabenyounes/log2test
